### ISSUE TITLE
parteditor mod is just ui tools

### ISSUE THREAD

**Issue by argon1321** [cucumber-sp/PartEditor#1]
when i downlaoded it it just became ui tools

**Comment by b4rthe1emy** [comment]
Same for me, I have two UI Tools now
![image](https://github.com/cucumber-sp/PartEditor/assets/132834665/b64ae1dd-b99d-4da1-9933-c02cfea200de)

**Comment by Ari-Khan** [comment]
I have the same issue. Is there any solution?

**Comment by Ari-Khan** [comment]
If you get the second edition of parteditor, the mod appears but it wont function.

**Comment by Ari-Khan** [comment]
I found the solution! The newest version of UI Tools is interfering with the PartEditor mod, so if you get the second version of UI tools and don't update it when prompted, the PartEditor will work fine.

**Comment by ghost** [comment]
@Proking4444 bruh UITools updates automatically for me

**Comment by Nighthunter22612** [comment]
Is it available for mobile?

**Comment by cucumber-sp** [comment]
Mods are not available for mobile
